version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(levelname)s - %(asctime)s - %(name)s - %(message)s"
        datefmt: '%Y-%m-%d %H:%M:%S'
    color:
        (): colorlog.ColoredFormatter
        format: "%(log_color)s%(levelname)s%(reset)s - %(asctime)s - %(name)s - %(message)s"
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: color
        stream: ext://sys.stdout

    output_file_handler:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: output.log
        encoding: utf8
        mode: w

    error_file_handler:
        class: logging.FileHandler
        level: WARNING
        formatter: simple
        filename: errors.log
        encoding: utf8
        mode: w

root:
    level: INFO
    handlers: [console, output_file_handler, error_file_handler]